config/routes.rb
Rails.application.routes.draw do
    resources :users
    get 'get_users/:id', to: 'users#get_users'
    
    resources :tweets
    root 'tweets#index'
    get 'get_tweets/:id', to: 'tweets#get_tweets'
    
    get 'top/main'
    post 'top/login'
    get 'top/logout'
    
    resources :likes
    root 'likes#index'
    get 'likes/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_one :profile
    has_many :likes
    has_many :like_tweets, through: :likes , source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @tweet = Tweet.find(params[:tweet_id])
        @user = User.find_by(uid: session[:login_uid])
        @user.like_tweets << @tweet
        redirect_to root_path
    end
    
    def destroy
        @tweet = Tweet.find(params[:id])
        @user = User.find_by(uid: session[:login_uid])
        @tweet.likes.find_by(user_id: @user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid]
           render 'main'
        else
            render 'login'
        end
    end
    
    def login
        if BCrypt::Password.new($login_password) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            redirect_to root_path
        end
    end
    
    def logout
       session.delete(:login_uid) 
       redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end
    
    def new
        @tweet = Tweet.new
    end
    
    def create
    
        logger.debug "---------------"
        @tweet = Tweet.new(message: params[:tweet][:message])
        if @tweet.save
            flash[:notice] = 'ツイートできました'
             redirect_to tweets_path
        else
            render 'new' 
        end
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.destroy
            flash[:notice] = 'ツイートを削除しました'
        end
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        logger.debug "---------------"
        uid = params[:user][:uid]
        pass =  params[:user][:pass]
        $login_password = BCrypt::Password.create(pass)
        @user =User.new(uid: uid,pass: $login_password)
        if @user.save
            flash[:notice] = 'ユーザ登録できました'
            redirect_to users_path
        else
            render 'new' 
        redirect_to root_path
        end
    end

    def destroy
        user = User.find(params[:id])
        if user.destroy
            flash[:notice] = 'ユーザを削除しました'
        end
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p>
    <% if session[:login_uid] %>
      ログイン中
    <% else %>
      ログインしていません
    <% end %>
  </body>
</html>

app/views/top/error.html.erb
ログイン失敗！
<p><%= link_to '戻る', :back %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'uid' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'pass' %>
    <%= password_field_tag :pass %>
        <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to 'ユーザ一覧', '/users' %></p>

app/views/top/main.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'uid' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'pass' %>
    <%= password_field_tag :pass %>
        <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to 'ユーザ一覧', '/users' %></p>

app/views/tweets/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% @tweets.each do |tweet| %>
  <p>
    <%= tweet.message %>
    <% if session[:login_uid] %>
      <%= link_to 'いいね', likes_path(tweet_id: tweet.id), method: :post %>
      <%= link_to 'いいね削除', like_path(tweet), method: :delete %>
      <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
    <% end %>
  </p>
<% end %>


<% if session[:login_uid] %>
  <p><%= link_to 'ツイートする', '/tweets/new' %>
  </p><%= link_to 'ログアウト', top_logout_path %>
<% else %>
  </p><%= link_to 'ログイン', '/top/main' %>
<% end %>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @tweet , url: {action: :create} do |f| %>
    <%= f.label :message, 'message' %>
    <%= f.text_field :message %>
    
    <%= f.submit 'つぶやく' %>
<% end %>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% @users.each do |user| %>
  <p>
    <%= user.uid %>
    <%= user.pass %>
    <%= link_to '削除', "/users/#{user.id}", method: :delete %>
  </p>
<% end %>

<p><%= link_to 'ユーザ登録', '/users/new' %></p>

<p><%= link_to 'メイン', root_path %></p>

app/views/users/new.html.erb
<% if @user.errors.present? %>
<h3>エラーがあります</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user , url: {action: :create} do |f| %>
    <%= f.label :uid, 'uid' %>
    <%= f.text_field :uid %>
    
    <%= f.label :pass, 'pass' %>
    <%= f.text_field :pass %>
    
    <%= f.submit '登録' %>
<% end %>